export const KPI_TRAIT_SCORES = {
  "KPI 1 (Body Positivity)": {
    "Sleep": 4,
    "Nutrition": 3,
    "Lingering Pain": 5,
    "Exercise Enjoyment (Affective Attitude – during workout)": 3,
    "Exercise Enjoyment (Affective Attitude – after workout)": 3,
    "Weather Impacts": 2,
    "OCEAN Extraversion": 3,
    "Social Exercise Orientation (Group-oriented vs Independent)": 3,
    "OCEAN Neuroticism (Stress Reactivity)": 5,
    "PERMA Positive Emotion": 4,
    "PERMA Accomplishment": 4,
    "Negative Affectivity (Type D)": 5,
    "Social Inhibition (Type D)": 4,
    "OCEAN Conscientiousness (fitness-adapted)": 3,
    "SDT Autonomy": 4,
    "SDT Competence": 5,
    "Mental Toughness (4Cs simplified)": 4,
    "Habit Formation": 3,
    "TTM Stage of Change": 3,
    "Obliger Tendency (Four Tendencies)": 3,
    "Workout adherence": 4,
    "Weight": 4,
    "Diet adherence": 3,
    "Self-confidence": 5
  },
  "KPI 2 (Self-Esteem Enhancement)": {
    "Sleep": 5,
    "Nutrition": 4,
    "Lingering Pain": 1,
    "Exercise Enjoyment (Affective Attitude – during workout)": 4,
    "Exercise Enjoyment (Affective Attitude – after workout)": 4,
    "Exercise Intensity Preference": 3,
    "Exercise Intensity Tolerance": 3,
    "Weather Impacts": 2,
    "Chronotype (Morningness–Eveningness)": 3,
    "OCEAN Extraversion": 4,
    "OCEAN Agreeableness": 3,
    "Social Exercise Orientation (Group-oriented vs Independent)": 3,
    "OCEAN Neuroticism (Stress Reactivity)": 1,
    "PERMA Positive Emotion": 5,
    "PERMA Accomplishment": 5,
    "Negative Affectivity (Type D)": 1,
    "Social Inhibition (Type D)": 2,
    "OCEAN Openness (fitness-adapted)": 3,
    "OCEAN Conscientiousness (fitness-adapted)": 5,
    "MBTI Judging/Perceiving": 3,
    "SDT Autonomy": 5,
    "SDT Competence": 5,
    "Mental Toughness (4Cs simplified)": 4,
    "Habit Formation": 3,
    "TTM Stage of Change": 4,
    "Obliger Tendency (Four Tendencies)": 3,
    "Workout adherence": 5,
    "Weight": 4,
    "Diet adherence": 4,
    "Self-confidence": 5
  },
  "KPI 3 (Stress Reduction)": {
    "Sleep": 5,
    "Nutrition": 4,
    "Lingering Pain": 1,
    "Exercise Enjoyment (Affective Attitude – during workout)": 4,
    "Exercise Enjoyment (Affective Attitude – after workout)": 4,
    "Exercise Intensity Preference": 3,
    "Exercise Intensity Tolerance": 3,
    "Weather Impacts": 2,
    "Chronotype (Morningness–Eveningness)": 3,
    "OCEAN Extraversion": 5,
    "OCEAN Agreeableness": 3,
    "Social Exercise Orientation (Group-oriented vs Independent)": 4,
    "OCEAN Neuroticism (Stress Reactivity)": 1,
    "PERMA Positive Emotion": 5,
    "PERMA Accomplishment": 4,
    "Negative Affectivity (Type D)": 1,
    "Social Inhibition (Type D)": 2,
    "OCEAN Openness (fitness-adapted)": 4,
    "OCEAN Conscientiousness (fitness-adapted)": 5,
    "MBTI Judging/Perceiving": 3,
    "SDT Autonomy": 5,
    "SDT Competence": 5,
    "Mental Toughness (4Cs simplified)": 5,
    "Habit Formation": 4,
    "TTM Stage of Change": 4,
    "Obliger Tendency (Four Tendencies)": 3,
    "Workout adherence": 5,
    "Weight": 3,
    "Diet adherence": 4,
    "Self-confidence": 5
  },
  "KPI 4 (Mood Improvement)": {
    "Sleep": 5,
    "Nutrition": 5,
    "Lingering Pain": 5,
    "Exercise Enjoyment (Affective Attitude – during workout)": 5,
    "Exercise Enjoyment (Affective Attitude – after workout)": 5,
    "Exercise Intensity Preference": 4,
    "Exercise Intensity Tolerance": 4,
    "Weather Impacts": 3,
    "Chronotype (Morningness–Eveningness)": 4,
    "OCEAN Extraversion": 5,
    "OCEAN Agreeableness": 4,
    "Social Exercise Orientation (Group-oriented vs Independent)": 5,
    "OCEAN Neuroticism (Stress Reactivity)": 1,
    "PERMA Positive Emotion": 5,
    "PERMA Accomplishment": 5,
    "Negative Affectivity (Type D)": 1,
    "Social Inhibition (Type D)": 1,
    "OCEAN Openness (fitness-adapted)": 5,
    "OCEAN Conscientiousness (fitness-adapted)": 5,
    "MBTI Judging/Perceiving": 4,
    "SDT Autonomy": 5,
    "SDT Competence": 5,
    "Mental Toughness (4Cs simplified)": 5,
    "Habit Formation": 5,
    "TTM Stage of Change": 5,
    "Obliger Tendency (Four Tendencies)": 3,
    "Workout adherence": 5,
    "Weight": 5,
    "Diet adherence": 5,
    "Self-confidence": 5
  },
  "KPI 5 (Increased Energy Levels)": {
    "Sleep": 5,
    "Nutrition": 5,
    "Lingering Pain": 5,
    "Exercise Enjoyment (Affective Attitude – during workout)": 5,
    "Exercise Enjoyment (Affective Attitude – after workout)": 5,
    "Exercise Intensity Preference": 4,
    "Exercise Intensity Tolerance": 4,
    "Weather Impacts": 3,
    "Chronotype (Morningness–Eveningness)": 4,
    "OCEAN Extraversion": 4,
    "OCEAN Agreeableness": 3,
    "Social Exercise Orientation (Group-oriented vs Independent)": 5,
    "OCEAN Neuroticism (Stress Reactivity)": 1,
    "PERMA Positive Emotion": 5,
    "PERMA Accomplishment": 5,
    "Negative Affectivity (Type D)": 1,
    "Social Inhibition (Type D)": 1,
    "OCEAN Openness (fitness-adapted)": 4,
    "OCEAN Conscientiousness (fitness-adapted)": 5,
    "MBTI Judging/Perceiving": 4,
    "SDT Autonomy": 5,
    "SDT Competence": 5,
    "Mental Toughness (4Cs simplified)": 5,
    "Habit Formation": 5,
    "TTM Stage of Change": 5,
    "Obliger Tendency (Four Tendencies)": 3,
    "Workout adherence": 5,
    "Weight": 4,
    "Diet adherence": 4,
    "Self-confidence": 5
  },
  "KPI 6 (Improved Sleep Quality)": {
    "Sleep": 5,
    "Nutrition": 4,
    "Lingering Pain": 1,
    "Exercise Enjoyment (Affective Attitude – during workout)": 3,
    "Exercise Enjoyment (Affective Attitude – after workout)": 4,
    "Exercise Intensity Preference": 3,
    "Exercise Intensity Tolerance": 3,
    "Weather Impacts": 3,
    "Chronotype (Morningness–Eveningness)": 5,
    "OCEAN Extraversion": 3,
    "OCEAN Agreeableness": 3,
    "Social Exercise Orientation (Group-oriented vs Independent)": 3,
    "OCEAN Neuroticism (Stress Reactivity)": 1,
    "PERMA Positive Emotion": 4,
    "PERMA Accomplishment": 4,
    "Negative Affectivity (Type D)": 1,
    "Social Inhibition (Type D)": 2,
    "OCEAN Openness (fitness-adapted)": 4,
    "OCEAN Conscientiousness (fitness-adapted)": 5,
    "MBTI Judging/Perceiving": 4,
    "SDT Autonomy": 5,
    "SDT Competence": 5,
    "Mental Toughness (4Cs simplified)": 4,
    "Habit Formation": 4,
    "TTM Stage of Change": 4,
    "Obliger Tendency (Four Tendencies)": 3,
    "Workout adherence": 4,
    "Weight": 3,
    "Diet adherence": 3,
    "Self-confidence": 4
  },
  "KPI 7 (Enhanced Cognitive Function)": {
    "Sleep": 5,
    "Nutrition": 5,
    "Lingering Pain": 2,
    "Exercise Enjoyment (Affective Attitude – during workout)": 4,
    "Exercise Enjoyment (Affective Attitude – after workout)": 3,
    "Exercise Intensity Preference": 3,
    "Exercise Intensity Tolerance": 3,
    "Weather Impacts": 2,
    "Chronotype (Morningness–Eveningness)": 3,
    "OCEAN Extraversion": 3,
    "OCEAN Agreeableness": 4,
    "Social Exercise Orientation (Group-oriented vs Independent)": 3,
    "OCEAN Neuroticism (Stress Reactivity)": 1,
    "PERMA Positive Emotion": 4,
    "PERMA Accomplishment": 4,
    "Negative Affectivity (Type D)": 1,
    "Social Inhibition (Type D)": 2,
    "OCEAN Openness (fitness-adapted)": 3,
    "OCEAN Conscientiousness (fitness-adapted)": 5,
    "MBTI Judging/Perceiving": 3,
    "SDT Autonomy": 4,
    "SDT Competence": 5,
    "Mental Toughness (4Cs simplified)": 4,
    "Habit Formation": 5,
    "TTM Stage of Change": 4,
    "Obliger Tendency (Four Tendencies)": 3,
    "Workout adherence": 5,
    "Weight": 4,
    "Diet adherence": 4,
    "Self-confidence": 4
  },
  "KPI 8 (Sense of Accomplishment)": {
    "Sleep": 5,
    "Nutrition": 5,
    "Lingering Pain": 1,
    "Exercise Enjoyment (Affective Attitude – during workout)": 5,
    "Exercise Enjoyment (Affective Attitude – after workout)": 5,
    "Exercise Intensity Preference": 4,
    "Exercise Intensity Tolerance": 5,
    "Weather Impacts": 1,
    "Chronotype (Morningness–Eveningness)": 3,
    "OCEAN Extraversion": 3,
    "OCEAN Agreeableness": 3,
    "Social Exercise Orientation (Group-oriented vs Independent)": 4,
    "OCEAN Neuroticism (Stress Reactivity)": 1,
    "PERMA Positive Emotion": 5,
    "PERMA Accomplishment": 5,
    "Negative Affectivity (Type D)": 1,
    "Social Inhibition (Type D)": 2,
    "OCEAN Openness (fitness-adapted)": 4,
    "OCEAN Conscientiousness (fitness-adapted)": 5,
    "MBTI Judging/Perceiving": 4,
    "SDT Autonomy": 4,
    "SDT Competence": 5,
    "Mental Toughness (4Cs simplified)": 5,
    "Habit Formation": 4,
    "TTM Stage of Change": 4,
    "Obliger Tendency (Four Tendencies)": 3,
    "Workout adherence": 5,
    "Weight": 3,
    "Diet adherence": 4,
    "Self-confidence": 4
  },
  "KPI 9 (Autonomy in Health Management)": {
    "Sleep": 5,
    "Nutrition": 5,
    "Lingering Pain": 1,
    "Exercise Enjoyment (Affective Attitude – during workout)": 5,
    "Exercise Enjoyment (Affective Attitude – after workout)": 5,
    "Exercise Intensity Preference": 5,
    "Exercise Intensity Tolerance": 5,
    "Weather Impacts": 1,
    "Chronotype (Morningness–Eveningness)": 3,
    "OCEAN Extraversion": 3,
    "OCEAN Agreeableness": 2,
    "Social Exercise Orientation (Group-oriented vs Independent)": 2,
    "OCEAN Neuroticism (Stress Reactivity)": 1,
    "PERMA Positive Emotion": 4,
    "PERMA Accomplishment": 5,
    "Negative Affectivity (Type D)": 1,
    "Social Inhibition (Type D)": 1,
    "OCEAN Openness (fitness-adapted)": 4,
    "OCEAN Conscientiousness (fitness-adapted)": 5,
    "MBTI Judging/Perceiving": 4,
    "SDT Autonomy": 4,
    "SDT Competence": 5,
    "Mental Toughness (4Cs simplified)": 5,
    "Habit Formation": 4,
    "TTM Stage of Change": 4,
    "Obliger Tendency (Four Tendencies)": 3,
    "Workout adherence": 5,
    "Weight": 3,
    "Diet adherence": 4,
    "Self-confidence": 4
  },
  "KPI 10 (Social Connectedness)": {
    "Sleep": 5,
    "Nutrition": 4,
    "Lingering Pain": 1,
    "Exercise Enjoyment (Affective Attitude – before workout)": 5,
    "Exercise Enjoyment (Affective Attitude – after workout)": 5,
    "Exercise Intensity Preference": 5,
    "Exercise Intensity Tolerance": 5,
    "Weather Impacts": 1,
    "Chronotype (Morningness–Eveningness)": 3,
    "OCEAN Extraversion": 5,
    "OCEAN Agreeableness": 5,
    "Social Exercise Orientation (Group-oriented vs Independent)": 5,
    "OCEAN Neuroticism (Stress Reactivity)": 1,
    "PERMA Positive Emotion": 5,
    "Negative Affectivity (Type D)": 1,
    "Social Inhibition (Type D)": 1,
    "OCEAN Openness (fitness-adapted)": 5,
    "OCEAN Conscientiousness (fitness-adapted)": 4,
    "SDT Competence": 5,
    "Habit Formation": 5,
    "Obliger Tendency (Four Tendencies)": 5,
    "Workout adherence": 5,
    "Self-confidence": 5
  },
  "KPI 11 (Body Fat Percentage)": {
    "Sleep": 5,
    "Nutrition": 5,
    "Lingering Pain": 4,
    "Exercise Enjoyment (Affective Attitude – during workout)": 3,
    "Exercise Enjoyment (Affective Attitude – after workout)": 3,
    "Exercise Intensity Preference": 3,
    "Exercise Intensity Tolerance": 3,
    "Weather Impacts": 2,
    "Chronotype (Morningness–Eveningness)": 2,
    "OCEAN Extraversion": 3,
    "OCEAN Agreeableness": 2,
    "Social Exercise Orientation (Group-oriented vs Independent)": 4,
    "OCEAN Neuroticism (Stress Reactivity)": 3,
    "PERMA Positive Emotion": 3,
    "PERMA Accomplishment": 4,
    "Negative Affectivity (Type D)": 4,
    "Social Inhibition (Type D)": 3,
    "OCEAN Openness (fitness-adapted)": 3,
    "OCEAN Conscientiousness (fitness-adapted)": 5,
    "MBTI Judging/Perceiving": 3,
    "SDT Autonomy": 5,
    "SDT Competence": 4,
    "Mental Toughness (4Cs simplified)": 4,
    "Habit Formation": 5,
    "TTM Stage of Change": 5,
    "Obliger Tendency (Four Tendencies)": 4,
    "Workout adherence": 5,
    "Weight": 5,
    "Diet adherence": 5,
    "Self-confidence": 4
  },
  "KPI 12 (Muscle Mass Gain)": {
    "Sleep": 5,
    "Nutrition": 5,
    "Lingering Pain": 1,
    "Exercise Enjoyment (Affective Attitude – during workout)": 5,
    "Exercise Enjoyment (Affective Attitude – after workout)": 5,
    "Exercise Intensity Preference": 5,
    "Exercise Intensity Tolerance": 5,
    "Weather Impacts": 1,
    "Chronotype (Morningness–Eveningness)": 4,
    "OCEAN Extraversion": 3,
    "OCEAN Agreeableness": 4,
    "Social Exercise Orientation (Group-oriented vs Independent)": 4,
    "OCEAN Neuroticism (Stress Reactivity)": 1,
    "PERMA Positive Emotion": 5,
    "PERMA Accomplishment": 5,
    "Negative Affectivity (Type D)": 1,
    "Social Inhibition (Type D)": 1,
    "OCEAN Openness (fitness-adapted)": 5,
    "OCEAN Conscientiousness (fitness-adapted)": 5,
    "MBTI Judging/Perceiving": 5,
    "SDT Autonomy": 5,
    "SDT Competence": 5,
    "Mental Toughness (4Cs simplified)": 5,
    "Habit Formation": 5,
    "TTM Stage of Change": 5,
    "Obliger Tendency (Four Tendencies)": 5,
    "Workout adherence": 5,
    "Diet adherence": 5,
    "Self-confidence": 5
  },
  "KPI 13 (Weight Management)": {
    "Sleep": 5,
    "Nutrition": 5,
    "Lingering Pain": 1,
    "Exercise Enjoyment (Affective Attitude – during workout)": 5,
    "Exercise Enjoyment (Affective Attitude – after workout)": 5,
    "Exercise Intensity Preference": 4,
    "Exercise Intensity Tolerance": 5,
    "Weather Impacts": 2,
    "Chronotype (Morningness–Eveningness)": 4,
    "OCEAN Extraversion": 4,
    "OCEAN Agreeableness": 3,
    "Social Exercise Orientation (Group-oriented vs Independent)": 4,
    "OCEAN Neuroticism (Stress Reactivity)": 2,
    "PERMA Positive Emotion": 5,
    "PERMA Accomplishment": 5,
    "Negative Affectivity (Type D)": 1,
    "Social Inhibition (Type D)": 2,
    "OCEAN Openness (fitness-adapted)": 4,
    "OCEAN Conscientiousness (fitness-adapted)": 5,
    "MBTI Judging/Perceiving": 4,
    "SDT Autonomy": 5,
    "SDT Competence": 5,
    "Mental Toughness (4Cs simplified)": 5,
    "Habit Formation": 5,
    "TTM Stage of Change": 5,
    "Obliger Tendency (Four Tendencies)": 4,
    "Workout adherence": 5,
    "Diet adherence": 5,
    "Self-confidence": 5
  },
  "KPI 14 (Strength Benchmarks)": {
    "Sleep": 5,
    "Nutrition": 5,
    "Lingering Pain": 1,
    "Exercise Enjoyment (Affective Attitude – during workout)": 4,
    "Exercise Enjoyment (Affective Attitude – after workout)": 5,
    "Exercise Intensity Preference": 4,
    "Exercise Intensity Tolerance": 5,
    "Weather Impacts": 3,
    "Chronotype (Morningness–Eveningness)": 3,
    "OCEAN Extraversion": 3,
    "OCEAN Agreeableness": 3,
    "Social Exercise Orientation (Group-oriented vs Independent)": 3,
    "OCEAN Neuroticism (Stress Reactivity)": 2,
    "PERMA Positive Emotion": 5,
    "PERMA Accomplishment": 5,
    "Negative Affectivity (Type D)": 1,
    "Social Inhibition (Type D)": 2,
    "OCEAN Openness (fitness-adapted)": 4,
    "OCEAN Conscientiousness (fitness-adapted)": 5,
    "MBTI Judging/Perceiving": 4,
    "SDT Autonomy": 5,
    "SDT Competence": 5,
    "Mental Toughness (4Cs simplified)": 5,
    "Habit Formation": 5,
    "TTM Stage of Change": 5,
    "Obliger Tendency (Four Tendencies)": 3,
    "Workout adherence": 5,
    "Weight": 4,
    "Diet adherence": 5,
    "Self-confidence": 5
  },
  "KPI 15 (Cardiovascular Endurance)": {
    "Sleep": 5,
    "Nutrition": 5,
    "Lingering Pain": 1,
    "Exercise Enjoyment (Affective Attitude – during workout)": 5,
    "Exercise Enjoyment (Affective Attitude – after workout)": 5,
    "Exercise Intensity Preference": 4,
    "Exercise Intensity Tolerance": 4,
    "Weather Impacts": 3,
    "Chronotype (Morningness–Eveningness)": 3,
    "OCEAN Extraversion": 4,
    "OCEAN Agreeableness": 2,
    "Social Exercise Orientation (Group-oriented vs Independent)": 3,
    "OCEAN Neuroticism (Stress Reactivity)": 1,
    "PERMA Positive Emotion": 5,
    "PERMA Accomplishment": 5,
    "Negative Affectivity (Type D)": 1,
    "Social Inhibition (Type D)": 1,
    "OCEAN Openness (fitness-adapted)": 3,
    "OCEAN Conscientiousness (fitness-adapted)": 5,
    "MBTI Judging/Perceiving": 3,
    "SDT Autonomy": 5,
    "SDT Competence": 5,
    "Mental Toughness (4Cs simplified)": 5,
    "Habit Formation": 5,
    "TTM Stage of Change": 5,
    "Obliger Tendency (Four Tendencies)": 3,
    "Workout adherence": 5,
    "Weight": 3,
    "Diet adherence": 4,
    "Self-confidence": 4
  },
  "KPI 16 (Sport Enhancement - Flexibility and Mobility)": {
    "Sleep": 4,
    "Nutrition": 4,
    "Lingering Pain": 1,
    "Exercise Enjoyment (Affective Attitude – during workout)": 5,
    "Exercise Enjoyment (Affective Attitude – after workout)": 5,
    "Exercise Intensity Preference": 2,
    "Exercise Intensity Tolerance": 2,
    "Weather Impacts": 2,
    "Chronotype (Morningness–Eveningness)": 2,
    "OCEAN Extraversion": 3,
    "OCEAN Agreeableness": 2,
    "Social Exercise Orientation (Group-oriented vs Independent)": 3,
    "OCEAN Neuroticism (Stress Reactivity)": 1,
    "PERMA Positive Emotion": 5,
    "PERMA Accomplishment": 5,
    "Negative Affectivity (Type D)": 1,
    "Social Inhibition (Type D)": 1,
    "OCEAN Openness (fitness-adapted)": 4,
    "OCEAN Conscientiousness (fitness-adapted)": 5,
    "MBTI Judging/Perceiving": 3,
    "SDT Autonomy": 5,
    "SDT Competence": 5,
    "Mental Toughness (4Cs simplified)": 3,
    "Habit Formation": 5,
    "TTM Stage of Change": 5,
    "Obliger Tendency (Four Tendencies)": 3,
    "Workout adherence": 5,
    "Weight": 2,
    "Diet adherence": 3,
    "Self-confidence": 4
  },
  "KPI 17 (Sport Enhancement – Balance & Coordination)": {
    "Sleep": 5,
    "Nutrition": 4,
    "Lingering Pain": 1,
    "Exercise Enjoyment (Affective Attitude – during workout)": 5,
    "Exercise Enjoyment (Affective Attitude – after workout)": 5,
    "Exercise Intensity Preference": 3,
    "Exercise Intensity Tolerance": 4,
    "Weather Impacts": 2,
    "Chronotype (Morningness–Eveningness)": 3,
    "OCEAN Extraversion": 4,
    "OCEAN Agreeableness": 3,
    "Social Exercise Orientation (Group-oriented vs Independent)": 4,
    "OCEAN Neuroticism (Stress Reactivity)": 1,
    "PERMA Positive Emotion": 4,
    "PERMA Accomplishment": 4,
    "Negative Affectivity (Type D)": 1,
    "Social Inhibition (Type D)": 1,
    "OCEAN Openness (fitness-adapted)": 3,
    "OCEAN Conscientiousness (fitness-adapted)": 5,
    "MBTI Judging/Perceiving": 4,
    "SDT Autonomy": 4,
    "SDT Competence": 5,
    "Mental Toughness (4Cs simplified)": 5,
    "Habit Formation": 5,
    "TTM Stage of Change": 5,
    "Obliger Tendency (Four Tendencies)": 3,
    "Workout adherence": 5,
    "Weight": 3,
    "Diet adherence": 4,
    "Self-confidence": 5
  },
  "KPI 18 (Sport Enhancement – Speed & Agility)": {
    "Sleep": 5,
    "Nutrition": 4,
    "Lingering Pain": 1,
    "Exercise Enjoyment (Affective Attitude – during workout)": 5,
    "Exercise Enjoyment (Affective Attitude – after workout)": 5,
    "Exercise Intensity Preference": 5,
    "Exercise Intensity Tolerance": 5,
    "Weather Impacts": 3,
    "Chronotype (Morningness–Eveningness)": 3,
    "OCEAN Extraversion": 4,
    "OCEAN Agreeableness": 3,
    "Social Exercise Orientation (Group-oriented vs Independent)": 4,
    "OCEAN Neuroticism (Stress Reactivity)": 1,
    "PERMA Positive Emotion": 5,
    "PERMA Accomplishment": 5,
    "Negative Affectivity (Type D)": 1,
    "Social Inhibition (Type D)": 1,
    "OCEAN Openness (fitness-adapted)": 4,
    "OCEAN Conscientiousness (fitness-adapted)": 5,
    "MBTI Judging/Perceiving": 4,
    "SDT Autonomy": 4,
    "SDT Competence": 5,
    "Mental Toughness (4Cs simplified)": 5,
    "Habit Formation": 5,
    "TTM Stage of Change": 5,
    "Obliger Tendency (Four Tendencies)": 3,
    "Workout adherence": 5,
    "Weight": 3,
    "Diet adherence": 4,
    "Self-confidence": 5
  }
};
